USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
    WITH WAREHOUSE_SIZE = 'X-SMALL' 
    AUTO_SUSPEND = 60       
    AUTO_RESUME = TRUE      
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.RAW;          -- Сырой слой
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.PROCESSED;    -- Чистовой слой (Silver)
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.PRESENTATION; -- Слой отчетов (Gold)
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.UTILS;      

CREATE OR REPLACE TABLE AIRLINE_DWH.UTILS.AUDIT_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    PROCEDURE_NAME VARCHAR,
    AFFECTED_ROWS NUMBER,
    OPERATION_TYPE VARCHAR,
    LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AIRLINE_DWH.RAW.FLIGHTS_RAW (
    ROW_INDEX NUMBER,
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE VARCHAR,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);

CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;


CREATE OR REPLACE TABLE AIRLINE_DWH.PROCESSED.DIM_PASSENGERS (
    PASSENGER_ID VARCHAR PRIMARY KEY,
    FULL_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR
);

CREATE OR REPLACE TABLE AIRLINE_DWH.PROCESSED.DIM_AIRPORTS (
    AIRPORT_NAME VARCHAR PRIMARY KEY, 
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR
);

-- Таблица ФАКТОВ: ПОЛЕТЫ (События)
CREATE OR REPLACE TABLE AIRLINE_DWH.PROCESSED.FACT_FLIGHTS (
    FLIGHT_ID VARCHAR DEFAULT UUID_STRING(),
    PASSENGER_ID VARCHAR,  
    AIRPORT_NAME VARCHAR,  
    DEPARTURE_DATE DATE,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE STREAM AIRLINE_DWH.RAW.FLIGHTS_STREAM ON TABLE AIRLINE_DWH.RAW.FLIGHTS_RAW;

CREATE OR REPLACE PROCEDURE AIRLINE_DWH.PROCESSED.PROCESS_FLIGHTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INT;
BEGIN
    IF (SYSTEM$STREAM_HAS_DATA('AIRLINE_DWH.RAW.FLIGHTS_STREAM')) THEN
        
        INSERT INTO AIRLINE_DWH.PROCESSED.DIM_PASSENGERS (PASSENGER_ID, FULL_NAME, GENDER, AGE, NATIONALITY)
        SELECT DISTINCT 
            PASSENGER_ID, 
            CONCAT(FIRST_NAME, ' ', LAST_NAME),
            GENDER, AGE, NATIONALITY
        FROM AIRLINE_DWH.RAW.FLIGHTS_STREAM
        WHERE METADATA$ACTION = 'INSERT'
        AND PASSENGER_ID NOT IN (SELECT PASSENGER_ID FROM AIRLINE_DWH.PROCESSED.DIM_PASSENGERS);

        INSERT INTO AIRLINE_DWH.PROCESSED.DIM_AIRPORTS (AIRPORT_NAME, COUNTRY_NAME, CONTINENT)
        SELECT DISTINCT 
            AIRPORT_NAME,
            COUNTRY_NAME,
            AIRPORT_CONTINENT
        FROM AIRLINE_DWH.RAW.FLIGHTS_STREAM
        WHERE METADATA$ACTION = 'INSERT'
        AND AIRPORT_NAME NOT IN (SELECT AIRPORT_NAME FROM AIRLINE_DWH.PROCESSED.DIM_AIRPORTS);

        INSERT INTO AIRLINE_DWH.PROCESSED.FACT_FLIGHTS 
        (PASSENGER_ID, AIRPORT_NAME, DEPARTURE_DATE, FLIGHT_STATUS, TICKET_TYPE, LOAD_TIMESTAMP)
        SELECT 
            PASSENGER_ID,
            AIRPORT_NAME,
            TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY'), 
            FLIGHT_STATUS,
            TICKET_TYPE,
            CURRENT_TIMESTAMP()
        FROM AIRLINE_DWH.RAW.FLIGHTS_STREAM
        WHERE METADATA$ACTION = 'INSERT';

        rows_inserted := SQLROWCOUNT;

        INSERT INTO AIRLINE_DWH.UTILS.AUDIT_LOG (PROCEDURE_NAME, AFFECTED_ROWS, OPERATION_TYPE)
        VALUES ('PROCESS_FLIGHTS', :rows_inserted, 'INSERT_FACTS');
        
        COMMIT;

        RETURN 'Processed Successfully. Facts inserted: ' || :rows_inserted;
    ELSE
        RETURN 'No data in stream';
    END IF;
END;
$$;


CREATE OR REPLACE ROW ACCESS POLICY AIRLINE_DWH.UTILS.ADMIN_ONLY_POLICY 
AS (val VARCHAR) RETURNS BOOLEAN ->
  CASE 
      WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE 
      ELSE FALSE 
  END;


ALTER TABLE AIRLINE_DWH.PROCESSED.DIM_AIRPORTS 
ADD ROW ACCESS POLICY AIRLINE_DWH.UTILS.ADMIN_ONLY_POLICY ON (COUNTRY_NAME);

CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.PRESENTATION.FLIGHTS_REPORT_VIEW AS
SELECT 
    a.COUNTRY_NAME, 
    COUNT(f.FLIGHT_ID) as TOTAL_FLIGHTS 
FROM AIRLINE_DWH.PROCESSED.FACT_FLIGHTS f
JOIN AIRLINE_DWH.PROCESSED.DIM_AIRPORTS a ON f.AIRPORT_NAME = a.AIRPORT_NAME
GROUP BY a.COUNTRY_NAME;