#!/bin/bash

. /common.sh

echo "Starting Spark Master at $SPARK_MASTER_HOST:$SPARK_MASTER_PORT..."
/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master \
    --ip $SPARK_MASTER_HOST \
    --port $SPARK_MASTER_PORT \
    --webui-port $SPARK_MASTER_WEBUI_PORT